[server]
showEmailPrompt = false
headless = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"

[theme]
primaryColor = "#059669"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
font = "sans serif"
